sync: bcook@Blakes-MacBook-Pro.local 2026-06-22 09:28:27

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,2 +1,10 @@
 #!/bin/sh
-gitleaks git
+if [ ! -f ~/.dotfiles.activate ]; then
+    exit
+fi
+
+if ! command -v gitleaks; then
+    echo "ERROR: gitleaks not found"
+else
+    gitleaks git
+fi
